### PR TITLE
React 15.5.4 compatibility

### LINKED ISSUE #7: Favicon: React.createClass is deprecated and will be removed in version 16
Just recently, with a new version of React, there is a warning coming up:

Warning: Favicon: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### PR DESCRIPTION
**Pull request by oflisback**
This commit fixes #7

Eliminated React.createClass warning using:
jscodeshift -t react-codemod/transforms/class.js

Also updated babel dependency.

### CODE REVIEW

**Comment by oflisback** [comment]
Hi @cezary yes I would gladly look after it if you like, thanks!

**Comment by cezary** [comment]
@oflisback getting a conflict with your fork on github:

image

**Comment by oflisback** [comment]
ok, renamed now.

**Comment by cezary** [comment]
Sorry, looks like renaming it doesn't work:

image

I think it needs to be removed for me to transfer it over.

**Comment by oflisback** [comment]
Ok, that's interesting, removed now. :)

**Comment by cezary** [comment]
Worked.

Already transferred npm ownership of the package, so you can publish any updates.

Thanks and good luck!

**Comment by oflisback** [comment]
Thank you for your confidence, good luck with whatever is consuming your time. :)

**Pull request closed without merging**
