### PR TITLE
Add TypeScript definition

### PR DESCRIPTION
**Pull request by ybiquitous**
Hi, I want to use this nice library in TypeScript, so I add the TypeScript definition.

I would be very happy if this PR would be accepted. 😊 

Please give me any feedback. Thanks.

### CODE REVIEW

**Comment by oflisback** [comment]
Thank you, I will try this out. :) I haven't really used typescript yet, do you have any advice on how to easily verify that the definitions work?

**Comment by ybiquitous** [comment]
> do you have any advice on how to easily verify that the definitions work?

OK 👍 

First, install packages to verify the definition:

```
npm install --save-dev typescript @types/react
```

Second, create a test file. For example:

```tsx
// test.tsx
import * as React from "react";
import Favicon from ".";

function App() {
  return <Favicon url="foo.png" />;
}
```

Last, run the test command:

```
./node_modules/.bin/tsc --jsx react --lib es2015 --noEmit test.tsx
```

When a test fails:

```diff
-return <Favicon url="foo.png" />;
+return <Favicon url_="foo.png" />;
```

```
$ ./node_modules/.bin/tsc --jsx react --lib es2015 --noEmit test.tsx
test.tsx:5:11 - error TS2322: Type '{ url_: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Favicon> & Readonly<FaviconProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'url_' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Favicon> & Readonly<FaviconProps> & Readonly<{ children?: ReactNode; }>'.

5   return <Favicon url_="foo.png" />;
            ~~~~~~~


Found 1 error.
```

**Comment by oflisback** [comment]
Awesome, will test and merge tomorrow, thank you!

**Comment by oflisback** [comment]
Thank you @ybiquitous!

**Comment by ybiquitous** [comment]
You are welcome!

**Comment by paterasMSFT** [comment]
@ybiquitous To detect the definition file, I had to add "node_modules/react-favicon" to my TypeScript include list. Is there a way to avoid that?

**Comment by ybiquitous** [comment]
@paterasMSFT It seems due to `"types": "react-favicon.d.ts"` has been removed via eab2a6fe4efc033783e9e8c618adeacd0c636670. See below:

https://github.com/oflisback/react-favicon/commit/eab2a6fe4efc033783e9e8c618adeacd0c636670#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L10

**Comment by oflisback** [comment]
Thank you for pointing that out, types has been added again and a version 0.0.22 is published to npm.

**Pull request merged**
